name = "Mojolicious-Plugin-Prometheus-Shared-FastMmap"
# badges = ["travis"]
module_maker="ModuleBuildTiny"
tag_format="v%v"
authority="cpan:TYLDUM"
license="artistic_2"
badges = ['metacpan']

[FileGatherer]
include_dotfiles = false

[Metadata]
x_deprecated = 1
